Publish issue and to make dev updated
Promact/oauth-client pull request #15
Opened 2017-02-05 08:52 UTC by siddharthashw

Fixes - #14 

Publish issue and to make dev updated

2017-02-05 09:38 UTC, siddharthashw commented
Don't accept this request for now.

2017-02-06 04:47 UTC, chintans requested changes

2017-02-06 04:47 UTC, chintans commented on Promact.OAuth.Client/src/Promact.OAuth.Client/Promact.OAuth.Client.nuspec
> +    <title>Promact-OAuth-SDK</title>
Why have you changed name?

2017-02-06 04:58 UTC, siddharthashw commented on Promact.OAuth.Client/src/Promact.OAuth.Client/Promact.OAuth.Client.nuspec
> +    <title>Promact-OAuth-SDK</title>
When you will add the environment variable of travis.  I will updated it and then will ask you to accept the request.

I changed the name for publishing it in nuget from my account

2017-02-06 05:00 UTC, chintans commented on Promact.OAuth.Client/src/Promact.OAuth.Client/Promact.OAuth.Client.nuspec
> +    <title>Promact-OAuth-SDK</title>
I have already added environment variable

2017-02-06 05:09 UTC, siddharthashw commented on Promact.OAuth.Client/src/Promact.OAuth.Client/Promact.OAuth.Client.nuspec
> +    <title>Promact-OAuth-SDK</title>
Now its updated. You can accept the PR

2017-02-06 05:22 UTC, chintans approved these changes

2017-02-06 05:22 UTC, merged