Updated README.md with relevant usage information
Promact/oauth-client pull request #25
Opened 2017-02-14 12:18 UTC by siddharthashw

Fixes - #24 

**1. README.md** - updated readme file and added with relevant usage information with one example.

2017-02-14 12:26 UTC, chintans requested changes

2017-02-14 12:26 UTC, chintans commented on README.md
> +    public Something(IUserModule user, IProjectModule project)
This is not a clear usage of the library. Are you assuming that anyone who is using will use it through Autofac or any other DI mechanism? 

Also, There is no instruction on how to initialize a module

2017-02-15 09:13 UTC, siddharthashw commented on README.md
> +    public Something(IUserModule user, IProjectModule project)
README.md - updated the instruction to initialization

2017-02-16 05:40 UTC, chintans approved these changes

2017-02-16 05:52 UTC, merged