Fixes - Issue #28
Promact/oauth-client pull request #37
Opened 2017-02-17 10:51 UTC by siddharthashw

Fixes - #28 

**1. StringConstant.cs** - Removed credentials from source code.
**2. IntegrationBaseProvider.cs** - Used environment variable.

2017-02-17 11:05 UTC, chintans requested changes

2017-02-17 11:05 UTC, chintans commented on Promact.OAuth.Client/src/Promact.OAuth.Client.Test/IntegrationBaseProvider.cs
> +            _client = new TokenClient(_discoveryClient.TokenEndpoint, Environment.GetEnvironmentVariable(_stringConstant.PromactOAuthClientId),
This file required no change

2017-02-17 11:05 UTC, chintans commented on Promact.OAuth.Client/src/Promact.OAuth.Client/Util/StringConstant/StringConstant.cs
> +                return "PromactOAuthClientId";
Test related constants should be in Test project. here you could return Environment.GetVariable

2017-02-17 11:07 UTC, siddharthashw commented on Promact.OAuth.Client/src/Promact.OAuth.Client/Util/StringConstant/StringConstant.cs
> +                return "PromactOAuthClientId";
ok

2017-02-17 11:07 UTC, siddharthashw commented on Promact.OAuth.Client/src/Promact.OAuth.Client.Test/IntegrationBaseProvider.cs
> +            _client = new TokenClient(_discoveryClient.TokenEndpoint, Environment.GetEnvironmentVariable(_stringConstant.PromactOAuthClientId),
ok

2017-02-20 02:59 UTC, chintans approved these changes

2017-02-20 02:59 UTC, merged